<?php
	//	INCLUDE
	/*
		SERVE PARA INSERIR ALGO COMUM A DUAS OU MAIS PAGINAS
		SEM PRECISAR ESCREVER O MESMO CODIGO EM CADA UM.
		GERALMENTE SE COLOCA OS ARQUIVOS QUE SERÃO INCLUIDOS
		COM EXTENSÃO '.inc'!
	*/
	
	include 'aula_16.inc'
?>